pingcap/website-docs

- .github/workflows/update.yml
This PR removes sync docs via payload temporarily and brings these key features:
- Upgrade actions/cache to @v2 #2
- Add schedule job (daily)
- Full docs retrieved
- Conditional Page Builds by Gatsby
> ci: add on schedule and Conditional Page Builds

- src/styles/templates/doc.scss
This reverts commit 18c811249d058aa65b94753033e8848c60defad0.
Reverted the commit #45. It is test PR, which will make the code block above the header with anchor not copyable.
> Revert "chore: adujst anchor positioning for fixed header layout (#45)"

- src/components/toc.js
- src/styles/components/toc.scss
- src/styles/templates/doc.scss
Add `display: none` on folded content to tell browser not to search folded content.
> Refine browser ctrl+f search results

- markdown-pages/download.js
If a file is renamed, the git info status will be `renamed`. We are missing the `renamed` status check and using markdown content cache for each incremental download, so the previous file won't be deleted.
Now add `renamed` status check, we can delete the previous file and download the new file.
> fix: add renamed status to delete previous file

- src/components/toc.js
As the title.
For now, it's annoyed when switching pages by click the links in TOC. This is because we use the native link tag to handle the switching.
It's needed to use the router helper `navigate` to handle this action. (For performance)
> perf: use navigate for internal toc links

- src/components/layout.js
As the title.
Sometimes, it's useful to provide pluggability in a website codebase so that the outside code (like browser extensions) can easily integrate into the website.
This PR is Is an initial attempt for the above desc.
> feat: set global for plugins use

- src/lib/__tests__/remarkSyntaxDiagram.js
- src/lib/remarkSyntaxDiagram.js
In an ENBF+diagram, components like `(x y z)*` is [currently rendered](https://github.com/pingcap/docs/issues/4389#issuecomment-762767158) like this:
```
>>--->---------------------v---><
(                       )
^--[ x ]-[ y ]-[ z ]--<
```
This is wrong as the lower part is traveled from right to left, so those following the railroad precisely will get the order `z y x` instead.
This PR changes the rendering to something like this instead to keep the LTR order.
```
>---------------------------v
/                             \
>>---^--->---[ x ]-[ y ]-[ z ]---v--->---><
(                         )
^-----------------------<
```
Single-node-wide components like `x*` are still rendered with the existing layout.
> remarkSyntaxDiagram: fix rendering of (x y z)*

- .github/workflows/dispatch.yml
- .github/workflows/update.yml
Remove the `event_type` limit from `update.yaml`, and customize `event_type` message.
The format of workflow name is `${repo}/${branch}-${sha}`, eg:
> chore: optimize workflow name

- .github/workflows/update.yml
- packages/download/http.js
- packages/download/index.js
- packages/download/package.json
- packages/download/utils.js
- yarn.lock
- Use `concurrency` instead of `softprops/turnstyle@v1`: 
- https://github.com/pingcap/website-docs/issues/216
- https://github.com/pingcap/website-docs/issues/215
- Rename `docs-cache` key for enable new cache
- Former cache contains docs that had been deleted(Dirty)
- Add `retrieveAllMDsFromZip`:
- `retrieveAllMDs` call Github API per file download, which easily exceeds API limit rate
- Now `retrieveAllMDsFromZip` can download and unzip archive file by calling Github API once per branch
- Temporarily enable on `pingcap/docs` and `pingcap/docs-cn`
> Refine retrive md file

- gatsby-config.js
- src/doc/comp/Toc.tsx
- src/doc/index.tsx
- src/lib/replaceInternalHref.js
`## origin title {#custom-id}`
will be translated to
`<path>#custom-id` in html
`replaceInternalHref` will transform `#stmt-summary-span-classversion-marknew-in-v304span` to `#stmt-summary-new-in-v304` under page scope.
> support markdown custom-id & enable `replaceInternalHref`

- .github/workflows/update.yml
- packages/download/index.js
- packages/download/utils.js
Now filter:tidb-cloud:en will remove `tidb-cloud` folder under taget src.
It will fix:
cloud `tidb-cloud/_index.md` will affect tidb index page.
> refine filter:tidb-cloud:en

- .github/workflows/update.yml
tidb-cloud folder should only exist on prod branch.
So we need to remove tidb-cloud folder on other branches.
> [temp]: rm tidb-cloud folder when building

- gatsby/plugin/syntax-diagram/index.ts
Signed-off-by: you06 <you1474600@gmail.com>
Now we transfer enbf into railroad in our doc, this PR support railroad diagram directly. Doc writes can choose either enbf or railroad now.
Source and diagram example:
> support railroad diagram

- .github/workflows/preview.yml
- .github/workflows/production.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> GitHub Actions: Deprecating save-state and set-output commands

- src/static/index.ts
`https://docs.pingcap.com/zh/tidb/dev/tidb-roadmap` is added in https://github.com/pingcap/docs-cn/pull/13942
> chore: add tidb roadmap to zh footer

- src/components/Dropdown/VersionSelect.tsx
Currently, it's difficult for users to find where are the archived docs of _TiDB in Kubernetes_ or _TiDB data migration_. This is because, when they click on the **Archived Docs** label in the version-select dropdown, they are taken to the archived docs of *TiDB*, rather than Kubernetes/DM.
This PR tries to improve user experience on this issue. If the doc type is tidb-in-kubernetes or dm, the archived URL should be the earliest archived version of the respective docs: v1.0 for TiDB in Kuberenetes and v1.0 for TiDB Data Migration.
> change the Archived Docs url in version-select dropdowns for kubernetes and dm docs

- src/components/Dropdown/VersionSelect.tsx
Show a `(DMR)` label for DMR versions like this: (only applicable to archived docs)
> show dmr label for version select in archived docs

- src/components/Dropdown/VersionSelect.tsx
Show DMR label in version select btn for [**archived docs site**](https://docs-archive.pingcap.com/tidb/v6.6/) only.
- Before: 
- After:
> show dmr label in version select btn

- src/components/Layout/HeaderNav.tsx
- src/components/Layout/MDXContent.tsx
> refine(layout/header): only enable `download` nav for zh doc

- src/components/MDXComponents/Pre.tsx
use `plaintext` when there's no language tag in the markdown
> fix: code high light

- gatsby-config.js
- src/components/Layout/HeaderNav.tsx
- src/components/Navigation/RightNav.tsx
This PR mainly does the following:
- Remove custom route change event name for gtm
- Remove unnecessary url search params for the playground link
> chore(gatsby, nav): update gtm configs and nav links

- src/styles/docTemplate.css
Avoid incorrect order of the footnotes list.
We need to use the latest mdx version and render plugin to fix this order problem which requires much more effort. So I prefer we update the unordered list style meanwhile we can get the correct reference as always.
> fix: footnotes list style

- src/templates/DocSearchTemplate.tsx
The previous code fails when `versions = ['v8.3', 'v8.1']` and `realVersion = 'release-8.1'`.
> fix: search redirects to the latest version when on stable version

- src/components/Layout/HeaderNav.tsx
This PR fixes the link of the home nav on the header for mobile.
> fix(layout/header): fix home link for mobile

- locale/en/translation.json
- locale/zh/translation.json
- src/components/Search/index.tsx
- src/templates/DocSearchTemplate.tsx
Close: https://github.com/pingcap/website-docs/issues/473
Preview: https://website-docs-git-feat-external-search-pingcap.vercel.app/
> feat: support external search

- locale/en/translation.json
This PR updates the community wording in translation.json, as requested by community operations:
Ask questions on Discord > Ask **the community**
> Update the community wording in translation.json

- gatsby/create-types.ts
- gatsby/toc.ts
- src/components/Layout/Seo.tsx
- src/components/Navigation/LeftNav.tsx
- src/components/Navigation/LeftNavTree.tsx
- src/shared/interface.ts
- src/templates/DocTemplate.tsx
> tweak: toc with heading & styles

- src/components/MDXComponents/LearningPath.tsx
Add column gap to learning path
> fix: learning path items gap

- src/components/Dropdown/VersionSelect.tsx
- Modified the rendering of DMR versions to only display when available, improving clarity and user experience.
- Wrapped DMR version items in a fragment for better structure and readability.
> refactor: update DMR version display logic in VersionSelect component

- src/components/Layout/HeaderNav.tsx
- src/shared/resources.ts
- Replaced dynamic URL generation for the AskTug link with a static URL in both desktop and mobile navigation.
- Removed the `generateAskTugUrl` function as it is no longer needed.
- Cleaned up the code by eliminating unused references to the AskTug forum in footer items.
> refactor: update HeaderNav component to use direct URL for AskTug

- src/shared/resources.ts
- Rename "TiDB Cloud Serverless" to "TiDB Cloud Starter" in footer
- Update corresponding URL from `/tidb-cloud-serverless/` to `/tidb-cloud-starter/`
> update footer product name from Serverless to Starter
