create-pages/doc.js, gatsby-config.js, gatsby-node.js, package.json, src/styles/components/navbar.scss, src/styles/templates/search.scss, yarn.lock
=> feat: create redirect for aliases

gatsby-config.js, package.json, yarn.lock
=> feat: generate sitemap

src/data/toolsLandingPage.js
=> data: add missing data

src/components/download.js, src/components/navbar.js, src/data/footer.js, src/data/tools.js
=> data: update links

markdown-pages/cli.js
=> fix: add download branch

create-pages/utils.js, markdown-pages/cli.js, package.json, scripts/download-dbaas-docs.sh, src/components/navbar.js
=> chore: add tidb cloud docs download script

.github/workflows/update.yml, create-pages/utils.js, markdown-pages/cli.js, markdown-pages/utils.js, package.json, scripts/download-dbaas-docs.sh, scripts/download-docs-dbaas.sh, src/components/footer.js, src/components/layout.js, src/components/navbar.js, src/components/search/result.js, src/components/toc.js, src/components/version.js, src/data/footer.js, src/intl/en.json, src/intl/zh.json, src/lib/docHelper.js, src/lib/replaceInternalHref.js, src/lib/version.js
=> chore: update links handle methods and footers

src/components/toc.js, src/components/version.js, src/lib/replaceInternalHref.js, src/lib/version.js
=> fix: update inner href in docs-dbaas

src/components/navbar.js, src/components/toc.js, src/data/footer.js, src/pages/search.js, src/styles/pages/search.scss, src/styles/templates/doc.scss, src/templates/doc.js
- update footer content
- add tidb cloud search result
- update active sidebar item
=> chore: add search result to tidbcloud

.github/workflows/update.yml
update gatsby cache version. PTAL
=> ci: update gatsby cache

.github/workflows/update.yml
Reverts pingcap/website-docs#59
=> Revert "ci: update gatsby cache"

create-pages/utils.js, src/components/footer.js, src/components/navbar.js, src/components/version.js, src/data/footer.js, src/data/tools.js, src/lib/version.js, src/pages/search.js, src/state/index.js
=> chore: create stable folder for each docs type

.github/workflows/update.yml
Reverts pingcap/website-docs#63
=> Revert "ci: remove delete params to keep stable files on server temporary"

.github/workflows/update.yml
=> ci: set crontab job to run ci at every 4 hours

.github/workflows/update.yml
=> chore: update cache key to make a full building

.github/workflows/dispatch.yml, .github/workflows/update.yml, markdown-pages/cli.js, markdown-pages/download.js, markdown-pages/utils.js, scripts/get-latest-commits.sh
=> feature: trigger docs building when pr pushed

.github/workflows/dispatch.yml, .github/workflows/update.yml, markdown-pages/cli.js, markdown-pages/download.js, markdown-pages/utils.js, scripts/get-latest-commits.sh
Reverts pingcap/website-docs#86
=> feat: trigger docs building when pr pushed

create-pages/utils.js, markdown-pages/cli.js, markdown-pages/utils.js, package.json, scripts/download-docs-dev-guide-zh.sh, src/components/navbar.js, src/components/version.js, src/intl/zh.json, src/lib/docHelper.js, src/lib/version.js, src/pages/search.js, src/templates/doc.js
- Dev guide docs only has Chinese version now.
- Only show dev guide type filter on Chinese search page
- Only show Cloud type filter on English search page
- Will expose '开发指南' on navbar after Agolia crawled `Dev Guide` docs
=> feat: add dev guide docs

.github/workflows/update.yml, markdown-pages/cli.js, scripts/get-latest-commits.sh, src/components/feedbackDocLink.js, src/components/improveDocLink.js, src/lib/docHelper.js, src/templates/doc.js
- remove dbaas docs from pingcap owner to tidbcloud owner
- get full download to update all commits for each repo-refs
=> chore: change owner of dbaas-docs to 'tidbcloud'

markdown-pages/cli.js, markdown-pages/utils.js
Details see related issue #105
=> Remove trailing whitespace

src/components/gitCommitInfo.js, src/intl/en.json, src/intl/zh.json, src/styles/templates/doc.scss, src/templates/doc.js
Show lasted commit info for each file using Github API  `GET /repos/:owner/:repo/commits`
=> chore: add latest commit message for each file

.github/workflows/dispatch.yml, .github/workflows/update.yml, README.md
use dispatch payload to make full/incremental download
=> chore: add full_download to dispatch payload

create-pages/utils.js, src/components/version.js, src/data/tools.js, src/lib/version.js
Reverts pingcap/website-docs#119
=> Revert "chore: change dm stable version to v2.0"

create-pages/doc.js, src/components/footer.js, src/components/layout.js, src/intl/en.json, src/intl/zh.json, src/pages/index.js, src/pages/search.js, src/pages/tools.js, src/styles/components/footer.scss, src/styles/components/version.scss, src/styles/global.scss, src/styles/pages/search.scss, src/templates/doc.js
=> chore: optimize language switcher

gatsby-browser.js, scripts/track.js
The `pageView` is a function to track user's behavior. Call `pageView` on each route change (`onRouteUpdate `)
=> chore: add chain track code

src/components/gitCommitInfo.js
Miss the ref of specific markdown file
=> chore: update file commit info fetch

README.md, src/components/shortcodes/index.js, src/components/shortcodes/simpleTab.js, src/styles/components/simpletab.scss
- Add shortcode to support tab panel feature. 
- Using some components of Materials-UI 
- See results on the images:
=> chore: support tab panel

markdown-pages/utils.js, src/components/deprecationNotice.js, src/intl/en.json, src/intl/zh.json, src/templates/doc.js
Requirement doc: https://pingcap.feishu.cn/docs/doccnOvoJhnY76Y19ZOJAUldwO0
=> chore: add deprecated notice banner for old docs versions

create-pages/utils.js, scripts/consolidate-duplicate-urls.sh, scripts/download-docs-tidb-operator-en.sh, scripts/download-docs-tidb-operator-zh.sh, src/lib/version.js
Reverts pingcap/website-docs#168
=> Revert "chore: add operator 1.2"

gatsby/create-pages.ts, gatsby/path.ts, gatsby/utils.ts, src/doc/comp/VersionSwitcher.tsx, src/doc/index.tsx, src/layout/comp/Navbar.tsx, src/lib/version.js, src/search/index.tsx, src/typing.ts
remove version tag  `public-preview`  from TiDB cloud docs
=> chore: tidb cloud remove public-preview version

src/layout/comp/Navbar.tsx, src/layout/comp/navbar.module.scss
=> [feat] Add `Try TiDB Cloud` button on NavBar if en pages

locale/en/translation.json, locale/zh/translation.json, src/doc/comp/CustomNotice.tsx
Update the text of DMR notice.
=> update dmr text

.github/workflows/update.yml
https://github.com/pingcap/website-docs/issues/224
https://github.com/pingcap/website-docs/issues/216
https://github.com/pingcap/website-docs/issues/215
=> re-enable Turnstyle

README.md, src/components/shortcodes/SimpleTab.tsx
support `SimpleTab` href props
=> [Update] SimpleTab add href props

locale/en/translation.json, locale/zh/translation.json, src/doc/comp/CustomNotice.tsx
Signed-off-by: Ran <huangran.alex@gmail.com>
=> update version notice

packages/download/index.js
Do remember revert this commit after v6.1 release
=> temporarily bypass docs dev version

src/layout/comp/footer.data.ts, src/layout/comp/footer.module.scss
Signed-off-by: xuliwenwenwen <liwen.xu@pingcap.com>
=> fix: contact link in chinese website

src/doc/comp/version-switcher.module.scss
Signed-off-by: xuliwenwenwen <liwen.xu@pingcap.com>
=> style: dropdown menu height optimized in left aside

src/layout/comp/footer.data.ts
Signed-off-by: xuliwenwenwen <liwen.xu@pingcap.com>
=> fix: footer link error in en

src/components/shortcodes/SimpleTab.tsx, src/state/index.js
Signed-off-by: xuliwenwenwen <liwen.xu@pingcap.com>
=> feat: add group id to simple tab component

gatsby-node.js, gatsby/create-pages.ts, src/apiReference/index.tsx
=> update cloud API reference URL

docs.json
Do not merge until release notes and search are ready.
=> add release-1.4 for tidb in k8s docs

src/components/Layout/MDXContent.tsx, src/components/Navigation/RightNav.tsx, src/utils/anchor.ts
https://github.com/pingcap/website-docs/issues/358
=> fix: anchor link with html

.github/workflows/production.yml
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
=> use macOS  for larger memory

src/components/Layout/MDXContent.tsx
anchor mismatch title position due to title with html tags
=> fix replaceInternalHref

.github/workflows/production.yml
This reverts commit 9762e23acb1b867ada3da3b89fea52d767fba9aa.
=> Revert "use macOS  for larger memory (#370)"

src/components/Avatar/Contributors.tsx
https://github.com/pingcap/docs-cn/issues/12315
=> Fix duplicated contributor issue

gatsby-config.js, locale/en/translation.json, locale/ja/translation.json, locale/zh/translation.json, src/components/Layout/Seo.tsx, src/static/index.ts, src/templates/DocTemplate.tsx
- Add `zh` to SEO
- Add archive title and desc to SEO
- Fix footer links
=> fix: seo, archive and footer links

src/components/Button/CopyBtn.tsx, src/components/Button/ScrollToTopBtn.tsx, src/components/Dropdown/VersionSelect.tsx, src/components/MDXComponents/DocHome.tsx, src/components/MDXComponents/SimpleTab.tsx, src/components/Navigation/LeftNavTree.tsx, src/components/Navigation/RightNav.tsx, src/utils/CustomHook.tsx
=> add classname and id

src/static/index.ts
=> update footer items

src/static/index.ts
Do not merge until https://github.com/pingcap/docs/pull/13153 is merged.
=> update footer to include roadmap

gatsby/plugin/content/index.ts
https://github.com/orgs/community/discussions/16925
=> feat: apply github md blockquote highlight

.github/workflows/docsearch.yml
Update the doc search script schedule from *At 23:30* to *At 06:00*
=> docsearch: update the doc search script schedule

src/components/Layout/Footer.tsx, src/static/index.ts, src/utils/index.ts
=> add privacy policy in footer

gatsby-config.js, src/components/Layout/Footer.tsx, src/components/Layout/Header.tsx, src/components/Layout/HeaderAction.tsx, src/components/Layout/HeaderNav.tsx, src/components/Navigation/RightNav.tsx, src/global.d.ts, src/utils/gtm.ts
This PR adds a universal GTM to the website and adds several tracking.
=> refine(gatsby, components): add universal GTM tracking

locale/en/translation.json, locale/ja/translation.json, locale/zh/translation.json, src/components/Campaign/FeedbackSurvey.tsx, src/templates/DocSearchTemplate.tsx, src/templates/DocTemplate.tsx
=> feat: provide popover for docs survey campaign

src/components/MDXComponents/DocHome.tsx
Closes #463 
This PR adds alt text to the icons on pingcap's doc website, making it easier for people who use screen readers to navigate the site.
=> feat: adding missing alt text 

gatsby/create-pages.ts
This PR removes docs dash banner because the campaign is over.
=> refactor(gatsby): remove banner

src/components/MDXComponents/EmailSubscriptionForm.tsx
This PR fixes the import statements in `EmailSubscriptionForm`
=> fix(components/email-subscription): import `Locale`

locale/en/translation.json, locale/zh/translation.json, src/components/MDXComponents/EmailSubscriptionForm.tsx
This PR improves the translations and styles of the `EmailSubscriptionForm` component.
=> refine(components/email-subscription): improve translations and styles

src/components/MDXComponents/EmailSubscriptionForm.tsx
=> fix(components/email-subscription): correct loading styles

src/components/Link.tsx, src/components/Navigation/LeftNavTree.tsx
- fix clickable range of navlink
related issue: #492
=> fix(nav): clickable range of link

src/static/index.ts
footer: use absolute links to prevent 404 errors on https://docs-archive.pingcap.com
=> footer: use absolute links

src/static/index.ts, src/templates/DocSearchTemplate.tsx
Related PR: https://github.com/pingcap/docs-staging/pull/85
Resolves https://github.com/pingcap/website-docs/issues/507
=> update: deprecated some search indexes

src/components/MDXComponents/DocHome.tsx, src/shared/resources.ts, src/templates/DocTemplate.tsx
This PR fixes wrong id for mdx and corrects the canonical link for archived docs.
=> fix(mdx, template): fix misc problems

src/styles/global.css
=> fix: font variant ligatures

src/templates/DocTemplate.tsx
- add the noindex meta tag for archived sites
=> tweak(seo): noindex for archived sites

docsearch/algolia_configs/en-tidb-v8.4.json, docsearch/algolia_configs/latest_commit.json, docsearch/algolia_configs/zh-tidb-v8.4.json, docsearch/run-algolia-crawler-fully.sh, docsearch/run-algolia-crawler-incrementally.sh
- Stop doc search for TiDB v8.3
- Add search for TiDB v8.4
=> doc-search: add search for TiDB v8.4 and stop v8.3 search

src/components/Navigation/LeftNavTree.tsx, src/shared/utils/index.ts
Close: https://github.com/pingcap/website-docs/issues/554
Fixed:
=> fix: nav layout

locale/ja/translation.json
=> tweak: ja survey desc

gatsby/create-pages.ts, src/components/Layout/MDXContent.tsx, src/shared/utils/index.ts
=> feat: ja doc home

.github/workflows/production.yml, gatsby-config.js, gatsby-node.js, package.json, sentry.config.js, yarn.lock
- integration with sentry for error & performance tracking
=> tweak: error & performance tracking

gatsby-node.js, src/components/Layout/HeaderAction.tsx, src/components/Navigation/RightNav.tsx, src/components/Search/index.tsx, src/shared/useReportReadingRate.ts, src/shared/utils/gtm.ts, src/templates/DocTemplate.tsx
- add Onsite/External search tracing
- remove some custom events
- ask_tidb_ai
replaced by:
- docs_download
replaced by:
- signin_click
- go_to_cloud_signup
replaced by:
- update gtm codes
- docs_navi_click
- docs_footer_click
- add reading rate which is a relative metric:
=> tweak(gtm): optimize events

src/shared/utils/index.ts
- use replace instead of replaceAll
=> fix: compatibility

src/components/Search/index.tsx, src/templates/DocSearchTemplate.tsx
- Fixed a bug where no results were returned in some scenarios during searching.
- Search state won't saved after refresh
https://github.com/user-attachments/assets/a0beeda1-3834-49ba-bed1-c4e298947d41
=> fix: doc search

src/components/Layout/Seo.tsx
Reverts pingcap/website-docs#578
=> Revert "fix: static bug"

gatsby/create-pages.ts, locale/en/translation.json, locale/ja/translation.json, locale/zh/translation.json, src/components/Layout/Banner/Banner.tsx, src/components/Layout/Header.tsx, src/components/Navigation/LeftNav.tsx, src/templates/404Template.tsx, src/templates/CloudAPIReferenceTemplate.tsx, src/templates/DocSearchTemplate.tsx, src/templates/DocTemplate.tsx
Preview: https://website-docs-git-feat-ai-lab-banner-pingcap.vercel.app/
Close #589
=> feat: add ai lab banner

src/components/MDXComponents/simple-tab.module.css
=> fix: tab max-width

src/components/Layout/HeaderAction.tsx
=> src: update console links for alicloud

.gemini/config.yaml
- add initial Gemini configuration file for code assist
=> feat: add initial Gemini configuration file for code assist

docsearch/algolia_configs/en-tidbcloud.json, docsearch/algolia_configs/latest_commit.json
Todo: update docsearch/algolia_configs/latest_commit.json
=>  agolia: use the v8.5 branch for TiDB Cloud docs

src/components/MDXComponents/CustomContent.tsx, src/components/MDXComponents/SimpleTab.tsx, src/components/MDXContent.tsx
Usage:
```<CustomContent language="en,zh">EN/ZH only</CustomContent>```
Resolve #631
=> Tweak custom content

.github/workflows/production.yml, gatsby/cloud-plan.ts, gatsby/create-pages.ts, gatsby/create-types.ts, gatsby/path.ts, gatsby/toc-filter.ts, gatsby/toc.ts, src/shared/interface.ts, src/shared/useCloudPlan.ts, src/templates/DocTemplate.tsx
=> tweak: set default plan base on the TOC
